name: dotnetapp
version: '0.1'
summary: .NET Bot
description: This is a sample .NET Core 2.1 application.
grade: devel
confinement: strict

apps:
  dotnetapp:
    command: dotnet fdd-app.dll

base: core18

apps:
  dotnet-hello:
    command: scd-app-plugin

parts:
  dotnet-hello:
    plugin: dotnet
    dotnet-runtime-version: 2.1.0
    source: .
    override-build: |
      dotnet build -c Release
      dotnet publish -c Release -o $SNAPCRAFT_PART_INSTALL --self-contained -r linux-x64
      chmod 0755 $SNAPCRAFT_PART_INSTALL/scd-app-plugin

