name: fdd-app-interface-30
base: core18
version: '0.1'
summary: .NET Bot
description: This is a sample .NET Core 2.1 application.
grade: devel
confinement: strict

apps:
  fdd-app-interface-30:
    command: fdd-app-interface
    environment:
      DOTNET_ROOT: $SNAP/dotnet-runtime-30

plugs:
  # Mount the content shared from dotnet-runtime-30 into $SNAP/dotnet-runtime-30
  dotnet-runtime-30:
    interface: content
    target: $SNAP/dotnet-runtime-30
    default-provider: dotnet-runtime-30

parts:
  fdd-app-interface:
    plugin: dump
    source: out/
    source-type: local
