name: fdd-app-interface-plugin
version: '0.1'
summary: .NET Bot
description: This is a sample .NET Core 2.1 application.
grade: devel
confinement: strict

apps:
  # You can't reference the dotnet muxer directory because it is contained outside of the snap
  # and snapcraft validates the existence of the command.
  fdd-app-interface-plugin:
    command: >
      env
      $SNAP/dotnet-runtime-21/dotnet
      $SNAP/fdd-app-interface-plugin.dll

plugs:
  # Mount the content shared from dotnet-runtime-21 into $SNAP/dotnet-runtime-21
  dotnet-runtime-22:
    interface: content
    target: $SNAP/dotnet-runtime-21
    default-provider: dotnet-runtime-21

base: core18

parts:
  fdd-app-interface-plugin:
    plugin: dotnet
    build-attributes: [no-runtime]
    source: .
