name: fdd-app-interface
version: '0.1'
summary: .NET Bot
description: This is a sample .NET Core 2.1 application.
grade: devel
confinement: strict

apps:
  fdd-app-interface:
    # not sure if this is the right way with the $snap usage?  Is there a way to set the "working directory"?
    command: >
      dotnet
      $SNAP/fdd-app.dll
    plugs:
      - dotnet-runtime-22

  test:
    command: dotnet

base: core18

parts:
  fdd-app:
    plugin: dump
    source: out/
    source-type: local

