name: fdd-app-interface
version: '0.1'
summary: .NET Bot
description: This is a sample .NET Core 2.1 application.
grade: devel
confinement: strict

apps:
#   fdd-app-interface:
#     command: >
#       dotnet
#       $SNAP/fdd-app-interface.dll
#     plugs:
#       - dotnet-runtime-22

  test:
    command: dotnet

base: core18

parts:
  fdd-app-interface:
    plugin: dump
    source: out/
    source-type: local
