name: fdd-app-interface
version: '0.1'
summary: .NET Bot
description: This is a sample .NET Core 2.1 application.
grade: devel
confinement: strict

# apps:
    # This doesn't work because the Muxer is outside of this snap.  You can't reference content outside of the app.
    # May be possible to write a wrapper for this.
#   fdd-app-interface:
#     command: >
#       dotnet
#       $SNAP/fdd-app-interface.dll
#     plugs:
#       - dotnet-runtime-22

  # test:
  #   command: $SNAP/dotnet-runtime-22/dotnet $SNAP/fdd-app-interface.dll

plugs:
  dotnet-runtime-22:
    interface: content
    target: $SNAP/dotnet-runtime-22
    default-provider: dotnet-runtime-22

base: core18

parts:
  fdd-app-interface:
    plugin: dump
    source: out/
    source-type: local
