name: scd-app
version: '0.1'
summary: .NET Bot
description: This is a sample .NET Core 2.1 application.
grade: devel
confinement: strict

base: core18

apps:
  dotnetapp:
    command: dotnetapp

parts:
  dotnetapp:
    plugin: dump
    source: out/
    source-type: local
    override-stage: |
      cd $SNAPCRAFT_PART_INSTALL
      chmod +x scd-app