name: scd-app
version: '0.1'
summary: .NET Bot
description: This is a sample .NET Core 2.1 application.
grade: devel
confinement: strict

base: core18

apps:
  scd-app:
    command: scd-app

parts:
  scd-app:
    plugin: dump
    source: out/
    source-type: local
    override-stage: |
      cd $SNAPCRAFT_PART_INSTALL
      chmod +x scd-app
    stage-packages:
      - libicu60
      - libssl1.0.0
      - libgssapi-krb5-2
      - liblttng-ust0
      - libstdc++6
      - zlib1g
      - libgcc1
      - libc6