name: scd-app
version: '0.1'
summary: .NET Bot
description: This is a sample .NET Core 2.1 application.
grade: devel
confinement: strict

base: core18

apps:
  scd-app:
    command: scd-app

parts:
  scd-app:
    plugin: dump
    source: out/
    source-type: local
    stage-packages:
      # The following are the `runtime-deps` dependencies.
      - libicu60
      - libssl1.0.0
      - libgssapi-krb5-2
      - liblttng-ust0
      - libstdc++6
      - zlib1g
      - libgcc1
      - libc6
      # The following are listed as missing libraries when only including the above.
      - libasn1-8-heimdal
      - libcurl4
      - libgssapi3-heimdal
      - libhcrypto4-heimdal
      - libheimbase1-heimdal
      - libheimntlm0-heimdal
      - libhx509-5-heimdal
      - libkrb5-26-heimdal
      - libldap-2.4-2
      - libnghttp2-14
      - libpsl5
      - libroken18-heimdal
      - librtmp1
      - libsasl2-2
      - libwind0-heimdal
